workflows:
  flutter-workflow:
    name: Horário Aulas
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_VERSION: stable
        ANDROID_HOME: /opt/android-sdk
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build Android
        script: |
          flutter build apk --release
      - name: Build iOS
        script: |
          flutter build ios --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa
 
publishing:
  email:
    recipients:
      - seu-email@dominio.com
